trame:
  cmd:
    - align-app
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --server
align-app:
  cmd:
    - align-app
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --server
